[versions]
agp = "8.2.0"
kotlin = "1.9.20"
compose = "1.5.4"
# Add Firebase versions
firebaseBom = "32.7.0"  # Firebase Bill of Materials
firebaseAuth = "22.3.0"
firebaseDatabase = "20.3.0"
firebaseMessaging = "23.3.1"

[libraries]
# ... your existing libraries ...

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }

[plugins]
# ... your existing plugins ...
google-services = { id = "com.google.gms.google-services", version = "4.4.0" }